### ISSUE TITLE
overleaf问题若干

### ISSUE THREAD

**Issue by Mathisdifficult** [Reanon/SEUThesisLatexTemplate#1]
感谢大佬提供的开源代码，但是部署发现有如下问题：
1.overleaf直接上传zip不能超过50MB，加入font文件夹后就超过了。
2.overleaf不支持中文文件夹，font文件夹内有2个中文文件夹，我删掉了 能顺利编译 不知道对显示效果有没有影响。

**Comment by Reanon** [comment]
fnot 文件夹是用于本地编译的，如果在线编译不需要 fnot/.

**Comment by Mathisdifficult** [comment]
> fnot 文件夹是用于本地编译的，如果在线编译不需要 fnot/.

好的，谢谢，问题出在我的这个在线overleaf没有Ubuntu Mono这个字体，编译到template模版下的\newcommand{\codefont}{\fontspec{Ubuntu Mono}} 这行代码会有问题，换成\newcommand{\codefont}{\fontspec{Consolas}} 解决了
