### ISSUE TITLE
空白页

### ISSUE THREAD

**Issue by Ignoranceemperor** [Reanon/SEUThesisLatexTemplate#8]
请问，每一章后边的空白页可以主动删除吗？

**Comment by Reanon** [comment]
每章首页要在奇数页上，是合理的

**Comment by Stitchsong** [comment]
每章首页要在奇数页上确实是合理的，但是盲审电子稿的时候老师很不喜欢有空白页，有没有什么方法主动去掉？感谢作者！

**Comment by Reanon** [comment]
让省稿老师自适应下，或者手动把空白页删除
